[project]
name = "PyTestArch"
version = "4.0.1"
requires-python = ">=3.11"
description = "Test framework for software architecture based on imports between modules"
authors = [{ name = "zyskarch", email = "zyskarch@gmail.com" }]
maintainers = [{ name = "zyskarch", email = "zyskarch@gmail.com" }]
readme = "README.md"
license = "Apache-2.0"

keywords = ["architecture", "test"]
classifiers = [
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Unit",
]

dependencies = ["networkx>=3.6"]

[project.optional-dependencies]
visualization = ["matplotlib>=3.11"]

[project.urls]
issues = "https://github.com/zyskarch/pytestarch/issues"
documentation = "https://zyskarch.github.io/pytestarch/latest"
repository = "https://github.com/zyskarch/pytestarch"

[tool.poetry.group.dev.dependencies]
zensical = "0.0.63"
mkdocstrings-python = "2.0.8"
mike = { git = "https://github.com/squidfunk/mike.git" }
nox = "2026.8.17"
pre-commit = "4.6.2"
pytest = "^9.1.1"
coverage = "^7.16.1"
ruff = "^0.16.8"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "F",      # Pyflakes
    "E",
    "W",      # Pylint Error, Warning
    "UP",     # pyupgrade
    "FURB",   # refurb
    "S",      # flake8-bandit
    "I",      # isort
    "RUF100", # Unneeded noqa
]
ignore = [
    "E501", # line too long -> handled by formatter
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = [
    "S101", # assert statement
    "E743", # ambiguous function name
]

[tool.ruff.lint.isort]
known-first-party = ["integration", "resources", "query_language"]
