name: Tests
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14", "3.15"]
        poetry-version: ["2.5.1"]
        os: [ubuntu-latest]
        include:
          - python-version: "3.14"
            poetry-version: "2.5.1"
            os: windows-latest
          - python-version: "3.14"
            poetry-version: "2.5.1"
            os: macos-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: setup poetry
        uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install dependencies
        run: poetry install --extras visualization
      - name: pytest
        run: poetry run pytest
